"""
Database layer for the Banking Customer Support
Multi-Agent System.

Uses SQLite for lightweight, file-based persistence.

Responsibilities:
- Create support_tickets table (if not exists)
- Insert new tickets (ID generated by DB)
- Query ticket status
"""

import sqlite3
from pathlib import Path
from typing import Optional


# ------------------------------------------------------------------
# DATABASE PATH SETUP (CLOUD-SAFE)
# ------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent
BASE_DIR.mkdir(parents=True, exist_ok=True)

DB_PATH = BASE_DIR / "support_tickets.db"


# ------------------------------------------------------------------
# DATABASE CONNECTION
# ------------------------------------------------------------------

def _get_connection():
    return sqlite3.connect(DB_PATH, check_same_thread=False)


# ------------------------------------------------------------------
# TABLE INITIALIZATION
# ------------------------------------------------------------------

def initialize_database():
    with _get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS support_tickets (
                ticket_number INTEGER PRIMARY KEY AUTOINCREMENT,
                issue_description TEXT NOT NULL,
                status TEXT NOT NULL
            )
        """)
        conn.commit()


# ------------------------------------------------------------------
# INSERT OPERATIONS
# ------------------------------------------------------------------

def insert_ticket(issue_description: str, status: str) -> int:
    """
    Inserts a new support ticket and returns the generated ticket number.
    """

    initialize_database()

    with _get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute("""
            INSERT INTO support_tickets (issue_description, status)
            VALUES (?, ?)
        """, (issue_description, status))
        conn.commit()

        return cursor.lastrowid


# ------------------------------------------------------------------
# QUERY OPERATIONS
# ------------------------------------------------------------------

def get_ticket_status(ticket_number: int) -> Optional[str]:
    initialize_database()

    with _get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute("""
            SELECT status
            FROM support_tickets
            WHERE ticket_number = ?
        """, (ticket_number,))
        row = cursor.fetchone()

        return row[0] if row else None
